print (10*'=','PAINEL DE ANIVERSÁRIANTES',10*'=')
dia = input('Qual seu dia de nascimento?')
mes = input('O mês por gentileza?')
ano = input('Ótimo, e o ano?')
print(10*'=')
print ('Seu aniversário no dia :',dia,'/',mes,'/',ano,'\nFoi registrado com sucesso!')
print ('...')
print ('Nós lembraremos de mandar um presente.')
print (10*'=','Até a próxima',10*'=')
