from random import choice

print(40*'=')
print('               SORTEADOR')
print(40*'=')
print('')
print('Digite o nome de cada participante:')
print('')
n1 = str(input('1º:'))
print('')
n2 = str(input('2º:'))
print('')
n3 = str(input('3º:'))
print('')
n4 = str(input('4º:'))
print('')
n5 = str(input('5º:'))
print('')
escolha = choice([n1, n2, n3, n4, n5])
print('')
print(n1, n2, n3, n4, n5)
print(f'Parabéns {escolha}! Você VENCEU!!!')
