print(40*'=')
print('ANALISADOR DE CIDADES SAGRADAS')
print(40*'=')
print('')
cidade = str(input('Digite o nome da sua cidade:').strip())
print('')
##print('True se ela for sagrada.\nFalse se for profana.')
print('')
print(cidade[:5].lower() == 'santo')
