print(10*'=','Analisador de Imputs',10*'=')
valor = input('Digite qualquer coisa:')
print(35*'=')
print('Deixou o campo em branco?', valor.isspace())
print('Digitou apenas números?', valor.isnumeric())
print('Digitou apenas letras?', valor.isalpha())
print('Digitou letras ou números?', valor.isalnum())
print('TEXTO EM CAPSLOCK?', valor.isupper())
print('...')
print('...')
print('...')
print('P.S: Baixo índice de criatividade da minha parte neste desafio.')
