print(40*'$')
print('        WELCOME TO HENDRIX SHOP')
print(40*'$')
print('')
marca = str(input('Qual a marca do veículo que você alugou?'))
dias = int(input('Quantos dias você utilizou o veículo?'))
km = float(input('Por quantos Kilometros você rodou?'))
print('')
print('Dê acordo com a tabela atual :\nR$60,00 diária\nR$0,15 p/KM')
print('')
print('O valor total a ser pago pelo periodo de\n aluguél do carro {} é de:'.format(marca))
print(40*'=')
print('')
print('               R${:.2f}'.format((dias * 60)+(km * 0.15)))
print('')
print(40*'=')